# Generated by Django 4.1.7 on 2023-04-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='menu_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
